# This is a basic workflow to upload files 
# from GitHub to server via GitHub Actions
name: Publish Website on DEV

# Controls when the workflow will run
on:

  # Triggers the workflow on push request event 
  # but only for the specific branch
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

# A workflow run is made up of one or more jobs 
# that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "SFTP-Deploy-Action"
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action

    # The type of runner that the job will run on 
    # (depends on server but usually this value is works)
    runs-on: ubuntu-latest

    timeout-minutes: 30
    
    # Steps represent a sequence of tasks 
    # that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0

          # Checkout a specific branch
          ref: test-branch

      # This is a composite GitHub Action (Linux runner) 
      # for deploying repository content to remote server
      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@main
        with:
          remote-protocol: "sftp"
          
          # Credentials for SFTP access to server using GitHub secrets
          remote-host: "sftp://180.222.138.9"
          remote-user: "azbftp01"
          remote-password: "Pah)P[&aC1-cWT#"

          # Path for specific folder on server for files deployment
          remote-path: "/main"

          # Port for SFTP access to server
          remote-port: 443
