on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: 180.222.138.9
        username: azbftp01
        password: Pah)P[&aC1-cWT#
        protocol: ftps
        port: 443 # todo replace with your web hosts ftps port
