on:
  push:
    branches:
      main

jobs:
    deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
              username: 'azbftp01'
              server: '180.222.138.9'
              port: '443'
              sftp_only: true
              password: 'Pah)P[&aC1-cWT#'
