  - name: SFTP uploader
  # You may pin to the exact commit or the version.
  # uses: wangyucode/sftp-upload-action@0ce8147ad8637906ceb7ebb272640ca45e4b2b31
  uses: wangyucode/sftp-upload-action@v2.0.2
  with:
    host: "180.222.138.9"
    port: 443
    username: "azbftp01"
    password: "Pah)P[&aC1-cWT#"
    localDir: '/'
    remoteDir: '/'
